[pytest]
# ==========================
# 1. 用例搜索路径
# ==========================
testpaths = tests/suites

# ==========================
# 2. 匹配测试文件
# ==========================
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# ==========================
# 3. 命令行默认参数（最重要）
# 运行 pytest 自动带这些参数
# ==========================
addopts =
    -v
    --alluredir=allure-results
    --clean-alluredir
    --no-header
    -n auto

# ==========================
# 4. 忽略哪些文件夹
# ==========================
norecursedirs =
    .venv
    __pycache__
    .git
    allure-report
    logs

# ==========================
# 5. 编码（防止中文乱码）
# ==========================

# ==========================
# 6. 自定义标记（可选）
# ==========================
markers =
    admin: 管理员用例
    user: 普通用户用例
    smoke: 冒烟用例